language: go
go:
  - "1.11"

# Secure environment variables causes choco install to hang indefinitely: https://travis-ci.community/t/choco-install-hangs-forever/307
matrix:
  include:
    - os: linux
      cache:
        directories:
          - $HOME/.cache/go-build
          - $TRAVIS_BUILD_DIR/web/node_modules
      before_install:
        - npm i -g npm@6.4.1
      env:
        secure: v8YTSShRorXHasSYxgMGqZ1WfmeRmnu87Ls7GGf7eFheV9AM2LBchWZ2U1S3/0gVtcRgUAadlvc0BUQkFczscnA8sUW1nX8A+Mosl4VLFh7QmXAvjjE31ubCS/MJz6w40EdYWYMzUfQ1S1K7jH55nAM2Z7IaKbzHagtpClu2hr+mCIRquZUYjE4/3mwxgpEMUa0QbHq8AE3KSevMQsksxJVzxv59i2EpwAjrSLlPMe28k8FX9mj0Q/k7qpy6AHveduXarcnTecNp+jbZx8D5cJQ94dFVnVOhjue4FTfmjmdTmvBWVWz+qjd5tLMZ1/KEhjji7349aSgnbL53FNTMmtKjJNF5YDCIXqfCN+jr+62VhA1pSjrgdYt+YDD1OXg6Tat/eF9Z6u6A8X7qWXqEnDFXFj02jdCvpd2isvW+l5zZXdQnf8vSfQ8ndRmeQwxx4Ntr89TBlPNJq44oMAMThRxfz1J6cPYgjS5gY5i8mqOUoYCEwSnFc+IO5/7Uxpb2DaPY4SLLAW4/wnbeEH3dN/m1Nknn8qF74LxBK4UwDX/Ucd5rY0rE9aRv17ph4vKBCOg4wCfw81n3ZgnlUTsinB4CR28/Z+90unxleQ45K9921rJMpyHTB7ywiENbGCQppJHJ84gOK5d6dtLK6F96vcaHiv6+q5pudwbu8X1YPvA=
    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $TRAVIS_BUILD_DIR/web/node_modules
      before_install:
        - npm i -g npm@6.4.1
    - os: windows
      cache:
        directories:
          - $HOME/AppData/Local/go-build
          - $TRAVIS_BUILD_DIR/web/node_modules
      before_install:
        - choco install nodejs-lts -y
        - choco install make -y
        - export PATH=$PATH:"/c/Program Files/nodejs"
        - node --version
        - npm --version
  fast_finish: true
  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - rpm
# TODO: Update goreleaser.yml and add when open sourced
#    - snapd
#
#env:
#- PATH=/snap/bin:$PATH
#
#install:
#- sudo snap install snapcraft --classic

# Install rice tool
before_script:
  - go install $TRAVIS_BUILD_DIR/vendor/github.com/GeertJohan/go.rice
  - go install $TRAVIS_BUILD_DIR/vendor/github.com/GeertJohan/go.rice/rice

script:
  - make ci
# choco install scripts points to private GH repo but windows cannot have secure env
# - if [[ $TRAVIS_OS_NAME == 'windows' ]]; then ./ci/travis-choco.sh; fi

deploy:
- provider: script
  skip_cleanup: true
  script: ./ci/travis-deploy.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
