apiVersion: v1
kind: Service
metadata:
  name: nginx-rc
  labels:
    project: dev-dashboard
spec:
  ports:
    - port: 80
      name: web
  selector:
    app: nginx-rc
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    project: dev-dashboard
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx-rc
  template:
    metadata:
      labels:
        app: nginx-rc
    spec:
      - image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP